/**
 * School Form 2 (SF2) Service
 * Handles attendance and daily school records.
 */
class SF2Service {
  /**
   * Generates a data structure for SF2 based on attendance logs.
   */
  generateSF2(schoolId, sectionId, month, attendanceLogs) {
    // Basic logic to group logs by student and calculate summary
    const summary = attendanceLogs.reduce((acc, log) => {
      if (!acc[log.studentId]) {
        acc[log.studentId] = {
          name: log.studentName,
          present: 0,
          absent: 0,
          tardy: 0
        };
      }

      if (log.status === 'present') acc[log.studentId].present++;
      else if (log.status === 'absent') acc[log.studentId].absent++;
      else if (log.status === 'tardy') acc[log.studentId].tardy++;

      return acc;
    }, {});

    return {
      form: "SF2",
      header: {
        schoolId,
        section: sectionId,
        month,
        year: new Date().getFullYear()
      },
      records: Object.keys(summary).map(id => ({
        studentId: id,
        ...summary[id]
      })),
      complianceNote: "Automatically generated by EduAI OS. Please verify with physical logbooks if required by local CO."
    };
  }

  /**
   * Generates SF1: School Register
   */
  generateSF1(schoolId, students) {
    return {
      form: "SF1",
      header: {
        schoolId,
        year: new Date().getFullYear()
      },
      records: students.map(s => ({
        id: s.id,
        name: s.name,
        gender: s.gender || 'N/A',
        birthDate: s.birthDate || 'N/A'
      }))
    };
  }

  /**
   * Generates SF5: Report on Promotion and Level of Proficiency
   */
  generateSF5(schoolId, grade, section, records) {
    return {
      form: "SF5",
      header: {
        schoolId,
        grade,
        section,
        year: new Date().getFullYear()
      },
      records: records.map(r => ({
        studentId: r.studentId,
        name: r.studentName,
        finalGrade: r.finalGrade,
        actionTaken: r.finalGrade >= 75 ? "PROMOTED" : "RETAINED"
      }))
    };
  }
}

module.exports = new SF2Service();
